### ISSUE TITLE
Error in `common_unix.go` for stat.Ctrim.Sec int32 vs int64

### ISSUE THREAD

**Issue by andreimerlescu** [andreimerlescu/checkfs#1]
When developing the [igo](https://github.com/andreimerlescu/igo) project `feature/fix` branch, I noticed that the new `make all` commands fails to compile the binaries for due to an error in the **checkfs** package that is being logged in this issue. 

The build fails to compile `GOOS=linux GOARCH=arm GOARM=7 go build -o bin/igo-linux-arm-7 .` due to the following error in `checkfs`. 

```log
# github.com/andreimerlescu/checkfs/common
../../go/pkg/mod/github.com/andreimerlescu/checkfs@v1.0.3/common/common_unix.go:53:19: cannot use stat.Ctim.Sec (variable of type int32) as int64 value in argument to time.Unix
../../go/pkg/mod/github.com/andreimerlescu/checkfs@v1.0.3/common/common_unix.go:53:34: cannot use stat.Ctim.Nsec (variable of type int32) as int64 value in argument to time.Unix
```

Apply a hotfix to the checkfs and bump its version to `v1.0.4` that includes expanded unit tests for this visibility. 

One part of this issue is the test results - though extensive - **does not catch this error**, so when you run `go test -count=1 ./...` you get: 

```log
ok  	github.com/andreimerlescu/checkfs	0.331s
ok  	github.com/andreimerlescu/checkfs/common	0.233s
ok  	github.com/andreimerlescu/checkfs/directory	0.515s
ok  	github.com/andreimerlescu/checkfs/file	0.423s
``` 

Definition of done means that I can run `GOOS=linux GOARCH=arm GOARM=7 go build -o bin/igo-linux-arm-7 .` without issue from checkfs. Then this issue is resolved.

**Comment by andreimerlescu** [comment]
I think the solution to this will be, 

```go
// GetCreationTime retrieves the creation time of a file or directory on Unix
func GetCreationTime(path string) (time.Time, error) {
	info, err := os.Stat(path)
	if err != nil {
		return time.Time{}, fmt.Errorf("failed to stat %s: %w", path, err)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return time.Time{}, fmt.Errorf("unable to get detailed stats for %s", path)
	}
	return time.Unix(int64(stat.Ctim.Sec), int64(stat.Ctim.Nsec)), nil
}
```

Where in the `return` statement we cast the `stat.Ctim.Sec` and `stat.Ctim.Nsec` into `int64`.

**Comment by andreimerlescu** [comment]
Additionally, the matrix of **GitHub Actions** will run the job from the _runner_ itself, were expanded to include MacOS Intel support, Ubuntu ARM support, and Windows support. 

```yml
os: [ubuntu-latest, ubuntu-arm, macos-13, macos-15, windows-2022, windows-2019]
go-version: [ '1.20.12', '1.21.7', '1.22.1', '1.23.4', '1.24.2']
```

```yml
distro:
  - image: rockylinux/rockylinux:9
    name: Rocky 9
  - image: amazonlinux:2023
    name: Amazon Linux 2023
  - image: centos:8
    name: CentOS 8
  - name: Suse Linux 8
    image: registry.suse.com/suse/sle15:15.5
  - name: Debian 12
    image: debian:bookworm
go-version: ['1.20.12', '1.21.7', '1.22.1', '1.23.2', '1.24.2']
```

This will increase the costs associated with fully testing checkfs as new enhancements are added, but the visibility in system-wide support of the package is justified.
